image: node:11

before_script:
  - npm ci

#cache:
#  paths:
#    - node_modules/

test:lint:
  script:
    - npm run lint

test:node:11:
  script:
    - npm run clean
    - npm run build
    - npm test

# LTS
test:node:10:
  image: node:10
  script:
    - npm run clean
    - npm run build
    - npm test

# LTS
test:node:8:
  image: node:8
  script:
    - npm run clean
    - npm run build
    - npm test
